export const foodNutrientMap: Record<string, string[]> = {
  eggs: ['protein', 'vitamin_d', 'b12', 'fat'],
  milk: ['calcium', 'vitamin_d', 'protein', 'b12'],
  banana: ['potassium', 'vitamin_c', 'magnesium'],
  oatmeal: ['fiber', 'iron', 'magnesium'],
  spinach: ['iron', 'magnesium', 'calcium', 'vitamin_c'],
  almonds: ['magnesium', 'vitamin_e', 'calcium'],
  salmon: ['omega3', 'vitamin_d', 'protein', 'b12'],
  tuna: ['omega3', 'vitamin_d', 'protein', 'b12'],
  sardines: ['omega3', 'calcium', 'vitamin_d'],
  yogurt: ['calcium', 'protein', 'b12'],
  cheese: ['calcium', 'protein', 'fat'],
  broccoli: ['vitamin_c', 'calcium', 'fiber'],
  orange: ['vitamin_c', 'fiber'],
  lemon: ['vitamin_c'],
  strawberry: ['vitamin_c', 'fiber'],
  bell_pepper: ['vitamin_c', 'fiber'],
  tomato: ['vitamin_c', 'potassium'],
  sweet_potato: ['vitamin_a', 'fiber', 'potassium'],
  carrot: ['vitamin_a', 'fiber'],
  kale: ['vitamin_c', 'calcium', 'iron', 'vitamin_k'],
  beef: ['iron', 'b12', 'zinc', 'protein'],
  chicken: ['protein', 'b12', 'zinc'],
  liver: ['iron', 'b12', 'vitamin_a', 'zinc'],
  lentils: ['iron', 'fiber', 'protein', 'magnesium'],
  beans: ['iron', 'fiber', 'protein', 'magnesium'],
  chickpeas: ['iron', 'fiber', 'protein', 'magnesium'],
  tofu: ['calcium', 'iron', 'protein'],
  avocado: ['fat', 'potassium', 'vitamin_e'],
  nuts: ['magnesium', 'vitamin_e', 'zinc', 'fat'],
  seeds: ['magnesium', 'zinc', 'iron', 'omega3'],
  chia: ['omega3', 'fiber', 'calcium', 'magnesium'],
  flax: ['omega3', 'fiber'],
  olive_oil: ['fat', 'vitamin_e'],
  butter: ['fat', 'vitamin_a'],
  whole_grain_bread: ['fiber', 'iron', 'magnesium'],
  brown_rice: ['magnesium', 'fiber', 'b6'],
  quinoa: ['protein', 'iron', 'magnesium', 'fiber'],
  tea: ['caffeine'],
  coffee: ['caffeine'],
  dark_chocolate: ['iron', 'magnesium', 'zinc'],
  mushrooms: ['vitamin_d', 'b12'],
  fortified_cereal: ['iron', 'b12', 'vitamin_d', 'calcium'],
};

export const supplementGuidance: Record<string, {
  bestTimeToTake: string;
  foodsToPair: string[];
  foodsToAvoid: string[];
  reasoning: string;
}> = {
  'vitamin d': {
    bestTimeToTake: 'Morning or midday with a meal containing fat',
    foodsToPair: ['eggs', 'avocado', 'nuts', 'olive_oil', 'salmon'],
    foodsToAvoid: [],
    reasoning: 'Vitamin D is fat-soluble and may improve absorption when taken with dietary fat.',
  },
  'vitamin d3': {
    bestTimeToTake: 'Morning or midday with a meal containing fat',
    foodsToPair: ['eggs', 'avocado', 'nuts', 'olive_oil', 'salmon'],
    foodsToAvoid: [],
    reasoning: 'Vitamin D3 is fat-soluble and may improve absorption when taken with dietary fat.',
  },
  iron: {
    bestTimeToTake: 'Morning on an empty stomach or with Vitamin C',
    foodsToPair: ['orange', 'lemon', 'strawberry', 'bell_pepper', 'broccoli'],
    foodsToAvoid: ['tea', 'coffee', 'milk', 'cheese', 'yogurt', 'calcium'],
    reasoning: 'Iron may reduce absorption when taken with calcium, tea, or coffee. Vitamin C may improve absorption.',
  },
  calcium: {
    bestTimeToTake: 'With food, preferably in the evening',
    foodsToPair: ['milk', 'yogurt', 'cheese', 'kale', 'broccoli'],
    foodsToAvoid: ['iron', 'spinach'],
    reasoning: 'Calcium may reduce iron absorption. Taking with food may improve tolerance.',
  },
  magnesium: {
    bestTimeToTake: 'Evening, preferably before bed',
    foodsToPair: ['almonds', 'banana', 'spinach', 'avocado', 'dark_chocolate'],
    foodsToAvoid: ['calcium'],
    reasoning: 'Magnesium may have a calming effect. Taking in the evening may support sleep.',
  },
  zinc: {
    bestTimeToTake: 'With a meal containing protein',
    foodsToPair: ['beef', 'chicken', 'seeds', 'nuts', 'chickpeas'],
    foodsToAvoid: ['iron', 'calcium'],
    reasoning: 'Zinc may reduce absorption when taken with high-dose iron or calcium.',
  },
  'omega-3': {
    bestTimeToTake: 'With a meal containing fat (breakfast or lunch)',
    foodsToPair: ['salmon', 'avocado', 'olive_oil', 'nuts', 'eggs'],
    foodsToAvoid: [],
    reasoning: 'Omega-3 fatty acids may improve absorption when taken with dietary fat.',
  },
  'vitamin b12': {
    bestTimeToTake: 'Morning on an empty stomach',
    foodsToPair: ['eggs', 'milk', 'beef', 'salmon', 'fortified_cereal'],
    foodsToAvoid: ['vitamin_c'],
    reasoning: 'High-dose Vitamin C may degrade Vitamin B12 in the digestive tract.',
  },
  b12: {
    bestTimeToTake: 'Morning on an empty stomach',
    foodsToPair: ['eggs', 'milk', 'beef', 'salmon', 'fortified_cereal'],
    foodsToAvoid: ['vitamin_c'],
    reasoning: 'High-dose Vitamin C may degrade Vitamin B12 in the digestive tract.',
  },
  'vitamin c': {
    bestTimeToTake: 'With meals throughout the day',
    foodsToPair: ['orange', 'broccoli', 'bell_pepper', 'strawberry', 'kale'],
    foodsToAvoid: ['b12'],
    reasoning: 'Vitamin C may improve iron absorption but may reduce B12 when taken together.',
  },
};

export const commonFoodNames: Record<string, string[]> = {
  egg: ['eggs'],
  eggs: ['eggs'],
  milk: ['milk'],
  banana: ['banana'],
  bananas: ['banana'],
  oatmeal: ['oatmeal'],
  oats: ['oatmeal'],
  spinach: ['spinach'],
  almonds: ['almonds'],
  almond: ['almonds'],
  salmon: ['salmon'],
  tuna: ['tuna'],
  yogurt: ['yogurt'],
  yoghurt: ['yogurt'],
  cheese: ['cheese'],
  broccoli: ['broccoli'],
  orange: ['orange'],
  oranges: ['orange'],
  lemon: ['lemon'],
  strawberry: ['strawberry'],
  strawberries: ['strawberry'],
  tomato: ['tomato'],
  tomatoes: ['tomato'],
  sweet_potato: ['sweet_potato'],
  sweet_potatoes: ['sweet_potato'],
  carrots: ['carrot'],
  carrot: ['carrot'],
  kale: ['kale'],
  beef: ['beef'],
  chicken: ['chicken'],
  liver: ['liver'],
  lentils: ['lentils'],
  lentil: ['lentils'],
  beans: ['beans'],
  chickpeas: ['chickpeas'],
  tofu: ['tofu'],
  avocado: ['avocado'],
  nuts: ['nuts'],
  seeds: ['seeds'],
  chia: ['chia'],
  flax: ['flax'],
  olive_oil: ['olive_oil'],
  butter: ['butter'],
  bread: ['whole_grain_bread'],
  rice: ['brown_rice'],
  quinoa: ['quinoa'],
  tea: ['tea'],
  coffee: ['coffee'],
  chocolate: ['dark_chocolate'],
  mushrooms: ['mushrooms'],
  cereal: ['fortified_cereal'],
  pepper: ['bell_pepper'],
  sardines: ['sardines'],
  bell_pepper: ['bell_pepper'],
};
